// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWic2qoFe-lt0J384AQ77Un6Ht34FPf-I',
    appId: '1:402082703433:web:3c8b8f9fc5cd5e10903798',
    messagingSenderId: '402082703433',
    projectId: 'vocalaiapp',
    storageBucket: 'vocalaiapp.appspot.com',
    authDomain: 'vocalaiapp.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxJCy1-HkGOdsSu8U7WDAB4I7TYpq8uVk',
    appId: '1:402082703433:android:32627a9ff9104ca9903798',
    messagingSenderId: '402082703433',
    projectId: 'vocalaiapp',
    storageBucket: 'vocalaiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWic2qoFe-lt0J384AQ77Un6Ht34FPf-I',
    appId: '1:402082703433:ios:de060f8ef310d741903798',
    messagingSenderId: '402082703433',
    projectId: 'vocalaiapp',
    storageBucket: 'vocalaiapp.appspot.com',
    iosBundleId: 'com.example.vocalEmotion',
  );
} 